batch_size: 512
dropout: 0.5
lr: 0.001
min_lr: 0.000001  
l2: 0.003

epoch: 100
patience: 3
early_stop: 5

num_layers: 1
num_heads: 2

q_i_cl_temp: 0.5 
q_i_cl_weight: 0.001

his_cl_temp: 0.1
his_cl_weight: 0.1

pred_hid_units: [ 1]

src_loss_weight: 1 # weight for the loss of search
